name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install fern
        run: npm install -g fern-api
      - name: fern generate
        run: fern generate
        env:
          FERN_TOKEN: dummy
      - name: Compile
        run: ./gradlew compileJava